### ISSUE TITLE
"npm run dev" does not work

### ISSUE THREAD

**Issue by murata2makoto** [amp-up-io/qti3-item-player-vue3#1]
I got this error message

npm error Missing script: "dev"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: C:\Users\eb2m-\AppData\Local\npm-cache\_logs\2024-10-15T08_43_55_405Z-debug-0.log

[2024-10-15T08_43_55_405Z-debug-0.log](https://github.com/user-attachments/files/17375404/2024-10-15T08_43_55_405Z-debug-0.log)

-bash-5.2$ npm run
Scripts available in qti3-test-vue3@0.1.3 via `npm run-script`:
  dev
    vite
  build
    vite build
  preview
    vite preview

The versions of node and npm in my computer are 20.18.0 and 10.9.0, respectively.

**Comment by paulgrudnitski** [comment]
qti3-item-player-vue3 package.json clearly shows the dev script on line 33.

https://github.com/amp-up-io/qti3-item-player-vue3/blob/main/package.json

**Comment by murata2makoto** [comment]
My apologies!  I used a different directory by mistake.
